name: build-test
on: [push]
jobs:
  build-javacode:
    name: javacode
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: make git
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16.0.0'
          architecture: x64
      - run: java -version
      - name: Make java-code
        run: make java-code
  build-pythoncode:
    name: pythoncode
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: make git
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: python --version
      - run: pip install -r requirements.txt
      - name: Make python-code
        run: make python-code
  build-csharpcode:
    name: csharpcode
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: make git
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: dotnet --version
      - name: Make csharp-code
        run: make csharp-code
