# Should have a step to deploy to gh-pages

name: build-test-deploy
on: [push]
# on:
#   push:
#     branches:
#       - source
#   pull_request:
#     branches:
#       - source
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Extract Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: node --version
      - name: Make code
        run: make code
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: env.BRANCH == 'main'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./website/dist
      #     publish_branch: master # default: gh-pages
      #     keep_files: false # default: false
      #     force_orphan: true
      #     commit_message: "GitHub CI Updates [ci skip]"
